// Generated by gencpp from file morai_msgs/FaultInjectionTireSrvRequest.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_FAULTINJECTIONTIRESRVREQUEST_H
#define MORAI_MSGS_MESSAGE_FAULTINJECTIONTIRESRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <morai_msgs/FaultInjection_Tire.h>

namespace morai_msgs
{
template <class ContainerAllocator>
struct FaultInjectionTireSrvRequest_
{
  typedef FaultInjectionTireSrvRequest_<ContainerAllocator> Type;

  FaultInjectionTireSrvRequest_()
    : request()  {
    }
  FaultInjectionTireSrvRequest_(const ContainerAllocator& _alloc)
    : request(_alloc)  {
  (void)_alloc;
    }



   typedef  ::morai_msgs::FaultInjection_Tire_<ContainerAllocator>  _request_type;
  _request_type request;





  typedef boost::shared_ptr< ::morai_msgs::FaultInjectionTireSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::FaultInjectionTireSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FaultInjectionTireSrvRequest_

typedef ::morai_msgs::FaultInjectionTireSrvRequest_<std::allocator<void> > FaultInjectionTireSrvRequest;

typedef boost::shared_ptr< ::morai_msgs::FaultInjectionTireSrvRequest > FaultInjectionTireSrvRequestPtr;
typedef boost::shared_ptr< ::morai_msgs::FaultInjectionTireSrvRequest const> FaultInjectionTireSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::FaultInjectionTireSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::FaultInjectionTireSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::FaultInjectionTireSrvRequest_<ContainerAllocator1> & lhs, const ::morai_msgs::FaultInjectionTireSrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.request == rhs.request;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::FaultInjectionTireSrvRequest_<ContainerAllocator1> & lhs, const ::morai_msgs::FaultInjectionTireSrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::FaultInjectionTireSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::FaultInjectionTireSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::FaultInjectionTireSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::FaultInjectionTireSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::FaultInjectionTireSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::FaultInjectionTireSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::FaultInjectionTireSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a7e45a698065b4e4cdd3e6ff1dc6b614";
  }

  static const char* value(const ::morai_msgs::FaultInjectionTireSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa7e45a698065b4e4ULL;
  static const uint64_t static_value2 = 0xcdd3e6ff1dc6b614ULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::FaultInjectionTireSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/FaultInjectionTireSrvRequest";
  }

  static const char* value(const ::morai_msgs::FaultInjectionTireSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::FaultInjectionTireSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "FaultInjection_Tire request\n"
"\n"
"================================================================================\n"
"MSG: morai_msgs/FaultInjection_Tire\n"
"int32 unique_id\n"
"int32 tire_index\n"
"\n"
"int32 fault_class\n"
"int32 fault_subclass\n"
;
  }

  static const char* value(const ::morai_msgs::FaultInjectionTireSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::FaultInjectionTireSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FaultInjectionTireSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::FaultInjectionTireSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::FaultInjectionTireSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "request: ";
    s << std::endl;
    Printer< ::morai_msgs::FaultInjection_Tire_<ContainerAllocator> >::stream(s, indent + "  ", v.request);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_FAULTINJECTIONTIRESRVREQUEST_H
