// Generated by gencpp from file morai_msgs/FaultStatusInfo_Sensor.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_FAULTSTATUSINFO_SENSOR_H
#define MORAI_MSGS_MESSAGE_FAULTSTATUSINFO_SENSOR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <morai_msgs/FaultStatusInfo_Overall.h>

namespace morai_msgs
{
template <class ContainerAllocator>
struct FaultStatusInfo_Sensor_
{
  typedef FaultStatusInfo_Sensor_<ContainerAllocator> Type;

  FaultStatusInfo_Sensor_()
    : sensor_id(0)
    , sensor()  {
    }
  FaultStatusInfo_Sensor_(const ContainerAllocator& _alloc)
    : sensor_id(0)
    , sensor(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _sensor_id_type;
  _sensor_id_type sensor_id;

   typedef  ::morai_msgs::FaultStatusInfo_Overall_<ContainerAllocator>  _sensor_type;
  _sensor_type sensor;





  typedef boost::shared_ptr< ::morai_msgs::FaultStatusInfo_Sensor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::FaultStatusInfo_Sensor_<ContainerAllocator> const> ConstPtr;

}; // struct FaultStatusInfo_Sensor_

typedef ::morai_msgs::FaultStatusInfo_Sensor_<std::allocator<void> > FaultStatusInfo_Sensor;

typedef boost::shared_ptr< ::morai_msgs::FaultStatusInfo_Sensor > FaultStatusInfo_SensorPtr;
typedef boost::shared_ptr< ::morai_msgs::FaultStatusInfo_Sensor const> FaultStatusInfo_SensorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::FaultStatusInfo_Sensor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::FaultStatusInfo_Sensor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::FaultStatusInfo_Sensor_<ContainerAllocator1> & lhs, const ::morai_msgs::FaultStatusInfo_Sensor_<ContainerAllocator2> & rhs)
{
  return lhs.sensor_id == rhs.sensor_id &&
    lhs.sensor == rhs.sensor;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::FaultStatusInfo_Sensor_<ContainerAllocator1> & lhs, const ::morai_msgs::FaultStatusInfo_Sensor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::FaultStatusInfo_Sensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::FaultStatusInfo_Sensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::FaultStatusInfo_Sensor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::FaultStatusInfo_Sensor_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::FaultStatusInfo_Sensor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::FaultStatusInfo_Sensor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::FaultStatusInfo_Sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9ffcbdb400d2f73cb504fbb8f540f234";
  }

  static const char* value(const ::morai_msgs::FaultStatusInfo_Sensor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9ffcbdb400d2f73cULL;
  static const uint64_t static_value2 = 0xb504fbb8f540f234ULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::FaultStatusInfo_Sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/FaultStatusInfo_Sensor";
  }

  static const char* value(const ::morai_msgs::FaultStatusInfo_Sensor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::FaultStatusInfo_Sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 sensor_id\n"
"FaultStatusInfo_Overall sensor\n"
"\n"
"\n"
"================================================================================\n"
"MSG: morai_msgs/FaultStatusInfo_Overall\n"
"bool status\n"
"int32[] fault_subclass\n"
;
  }

  static const char* value(const ::morai_msgs::FaultStatusInfo_Sensor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::FaultStatusInfo_Sensor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sensor_id);
      stream.next(m.sensor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FaultStatusInfo_Sensor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::FaultStatusInfo_Sensor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::FaultStatusInfo_Sensor_<ContainerAllocator>& v)
  {
    s << indent << "sensor_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sensor_id);
    s << indent << "sensor: ";
    s << std::endl;
    Printer< ::morai_msgs::FaultStatusInfo_Overall_<ContainerAllocator> >::stream(s, indent + "  ", v.sensor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_FAULTSTATUSINFO_SENSOR_H
