// Generated by gencpp from file morai_msgs/FaultStatusInfo_Overall.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_FAULTSTATUSINFO_OVERALL_H
#define MORAI_MSGS_MESSAGE_FAULTSTATUSINFO_OVERALL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace morai_msgs
{
template <class ContainerAllocator>
struct FaultStatusInfo_Overall_
{
  typedef FaultStatusInfo_Overall_<ContainerAllocator> Type;

  FaultStatusInfo_Overall_()
    : status(false)
    , fault_subclass()  {
    }
  FaultStatusInfo_Overall_(const ContainerAllocator& _alloc)
    : status(false)
    , fault_subclass(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _fault_subclass_type;
  _fault_subclass_type fault_subclass;





  typedef boost::shared_ptr< ::morai_msgs::FaultStatusInfo_Overall_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::FaultStatusInfo_Overall_<ContainerAllocator> const> ConstPtr;

}; // struct FaultStatusInfo_Overall_

typedef ::morai_msgs::FaultStatusInfo_Overall_<std::allocator<void> > FaultStatusInfo_Overall;

typedef boost::shared_ptr< ::morai_msgs::FaultStatusInfo_Overall > FaultStatusInfo_OverallPtr;
typedef boost::shared_ptr< ::morai_msgs::FaultStatusInfo_Overall const> FaultStatusInfo_OverallConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::FaultStatusInfo_Overall_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::FaultStatusInfo_Overall_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::FaultStatusInfo_Overall_<ContainerAllocator1> & lhs, const ::morai_msgs::FaultStatusInfo_Overall_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.fault_subclass == rhs.fault_subclass;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::FaultStatusInfo_Overall_<ContainerAllocator1> & lhs, const ::morai_msgs::FaultStatusInfo_Overall_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::FaultStatusInfo_Overall_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::FaultStatusInfo_Overall_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::FaultStatusInfo_Overall_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::FaultStatusInfo_Overall_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::FaultStatusInfo_Overall_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::FaultStatusInfo_Overall_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::FaultStatusInfo_Overall_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49c4320f71e991dad6fc697eff35406f";
  }

  static const char* value(const ::morai_msgs::FaultStatusInfo_Overall_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49c4320f71e991daULL;
  static const uint64_t static_value2 = 0xd6fc697eff35406fULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::FaultStatusInfo_Overall_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/FaultStatusInfo_Overall";
  }

  static const char* value(const ::morai_msgs::FaultStatusInfo_Overall_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::FaultStatusInfo_Overall_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status\n"
"int32[] fault_subclass\n"
;
  }

  static const char* value(const ::morai_msgs::FaultStatusInfo_Overall_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::FaultStatusInfo_Overall_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.fault_subclass);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FaultStatusInfo_Overall_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::FaultStatusInfo_Overall_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::FaultStatusInfo_Overall_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    s << indent << "fault_subclass[]" << std::endl;
    for (size_t i = 0; i < v.fault_subclass.size(); ++i)
    {
      s << indent << "  fault_subclass[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.fault_subclass[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_FAULTSTATUSINFO_OVERALL_H
