// Generated by gencpp from file morai_msgs/FaultInjection_Tire.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_FAULTINJECTION_TIRE_H
#define MORAI_MSGS_MESSAGE_FAULTINJECTION_TIRE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace morai_msgs
{
template <class ContainerAllocator>
struct FaultInjection_Tire_
{
  typedef FaultInjection_Tire_<ContainerAllocator> Type;

  FaultInjection_Tire_()
    : unique_id(0)
    , tire_index(0)
    , fault_class(0)
    , fault_subclass(0)  {
    }
  FaultInjection_Tire_(const ContainerAllocator& _alloc)
    : unique_id(0)
    , tire_index(0)
    , fault_class(0)
    , fault_subclass(0)  {
  (void)_alloc;
    }



   typedef int32_t _unique_id_type;
  _unique_id_type unique_id;

   typedef int32_t _tire_index_type;
  _tire_index_type tire_index;

   typedef int32_t _fault_class_type;
  _fault_class_type fault_class;

   typedef int32_t _fault_subclass_type;
  _fault_subclass_type fault_subclass;





  typedef boost::shared_ptr< ::morai_msgs::FaultInjection_Tire_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::FaultInjection_Tire_<ContainerAllocator> const> ConstPtr;

}; // struct FaultInjection_Tire_

typedef ::morai_msgs::FaultInjection_Tire_<std::allocator<void> > FaultInjection_Tire;

typedef boost::shared_ptr< ::morai_msgs::FaultInjection_Tire > FaultInjection_TirePtr;
typedef boost::shared_ptr< ::morai_msgs::FaultInjection_Tire const> FaultInjection_TireConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::FaultInjection_Tire_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::FaultInjection_Tire_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::FaultInjection_Tire_<ContainerAllocator1> & lhs, const ::morai_msgs::FaultInjection_Tire_<ContainerAllocator2> & rhs)
{
  return lhs.unique_id == rhs.unique_id &&
    lhs.tire_index == rhs.tire_index &&
    lhs.fault_class == rhs.fault_class &&
    lhs.fault_subclass == rhs.fault_subclass;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::FaultInjection_Tire_<ContainerAllocator1> & lhs, const ::morai_msgs::FaultInjection_Tire_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::FaultInjection_Tire_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::FaultInjection_Tire_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::FaultInjection_Tire_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::FaultInjection_Tire_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::FaultInjection_Tire_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::FaultInjection_Tire_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::FaultInjection_Tire_<ContainerAllocator> >
{
  static const char* value()
  {
    return "390f98f80684e87e512f8ec107a7d8c1";
  }

  static const char* value(const ::morai_msgs::FaultInjection_Tire_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x390f98f80684e87eULL;
  static const uint64_t static_value2 = 0x512f8ec107a7d8c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::FaultInjection_Tire_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/FaultInjection_Tire";
  }

  static const char* value(const ::morai_msgs::FaultInjection_Tire_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::FaultInjection_Tire_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 unique_id\n"
"int32 tire_index\n"
"\n"
"int32 fault_class\n"
"int32 fault_subclass\n"
;
  }

  static const char* value(const ::morai_msgs::FaultInjection_Tire_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::FaultInjection_Tire_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.unique_id);
      stream.next(m.tire_index);
      stream.next(m.fault_class);
      stream.next(m.fault_subclass);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FaultInjection_Tire_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::FaultInjection_Tire_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::FaultInjection_Tire_<ContainerAllocator>& v)
  {
    s << indent << "unique_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.unique_id);
    s << indent << "tire_index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.tire_index);
    s << indent << "fault_class: ";
    Printer<int32_t>::stream(s, indent + "  ", v.fault_class);
    s << indent << "fault_subclass: ";
    Printer<int32_t>::stream(s, indent + "  ", v.fault_subclass);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_FAULTINJECTION_TIRE_H
