// Generated by gencpp from file morai_msgs/FaultInjectionTireSrv.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_FAULTINJECTIONTIRESRV_H
#define MORAI_MSGS_MESSAGE_FAULTINJECTIONTIRESRV_H

#include <ros/service_traits.h>


#include <morai_msgs/FaultInjectionTireSrvRequest.h>
#include <morai_msgs/FaultInjectionTireSrvResponse.h>


namespace morai_msgs
{

struct FaultInjectionTireSrv
{

typedef FaultInjectionTireSrvRequest Request;
typedef FaultInjectionTireSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FaultInjectionTireSrv
} // namespace morai_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::morai_msgs::FaultInjectionTireSrv > {
  static const char* value()
  {
    return "4c1cd51f8732dd56891a353f6f931b8a";
  }

  static const char* value(const ::morai_msgs::FaultInjectionTireSrv&) { return value(); }
};

template<>
struct DataType< ::morai_msgs::FaultInjectionTireSrv > {
  static const char* value()
  {
    return "morai_msgs/FaultInjectionTireSrv";
  }

  static const char* value(const ::morai_msgs::FaultInjectionTireSrv&) { return value(); }
};


// service_traits::MD5Sum< ::morai_msgs::FaultInjectionTireSrvRequest> should match
// service_traits::MD5Sum< ::morai_msgs::FaultInjectionTireSrv >
template<>
struct MD5Sum< ::morai_msgs::FaultInjectionTireSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::morai_msgs::FaultInjectionTireSrv >::value();
  }
  static const char* value(const ::morai_msgs::FaultInjectionTireSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::morai_msgs::FaultInjectionTireSrvRequest> should match
// service_traits::DataType< ::morai_msgs::FaultInjectionTireSrv >
template<>
struct DataType< ::morai_msgs::FaultInjectionTireSrvRequest>
{
  static const char* value()
  {
    return DataType< ::morai_msgs::FaultInjectionTireSrv >::value();
  }
  static const char* value(const ::morai_msgs::FaultInjectionTireSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::morai_msgs::FaultInjectionTireSrvResponse> should match
// service_traits::MD5Sum< ::morai_msgs::FaultInjectionTireSrv >
template<>
struct MD5Sum< ::morai_msgs::FaultInjectionTireSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::morai_msgs::FaultInjectionTireSrv >::value();
  }
  static const char* value(const ::morai_msgs::FaultInjectionTireSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::morai_msgs::FaultInjectionTireSrvResponse> should match
// service_traits::DataType< ::morai_msgs::FaultInjectionTireSrv >
template<>
struct DataType< ::morai_msgs::FaultInjectionTireSrvResponse>
{
  static const char* value()
  {
    return DataType< ::morai_msgs::FaultInjectionTireSrv >::value();
  }
  static const char* value(const ::morai_msgs::FaultInjectionTireSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_FAULTINJECTIONTIRESRV_H
