// Generated by gencpp from file morai_msgs/FaultInjectionSensorSrv.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_FAULTINJECTIONSENSORSRV_H
#define MORAI_MSGS_MESSAGE_FAULTINJECTIONSENSORSRV_H

#include <ros/service_traits.h>


#include <morai_msgs/FaultInjectionSensorSrvRequest.h>
#include <morai_msgs/FaultInjectionSensorSrvResponse.h>


namespace morai_msgs
{

struct FaultInjectionSensorSrv
{

typedef FaultInjectionSensorSrvRequest Request;
typedef FaultInjectionSensorSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FaultInjectionSensorSrv
} // namespace morai_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::morai_msgs::FaultInjectionSensorSrv > {
  static const char* value()
  {
    return "7a22d370d63968f482f03b961f96bf2e";
  }

  static const char* value(const ::morai_msgs::FaultInjectionSensorSrv&) { return value(); }
};

template<>
struct DataType< ::morai_msgs::FaultInjectionSensorSrv > {
  static const char* value()
  {
    return "morai_msgs/FaultInjectionSensorSrv";
  }

  static const char* value(const ::morai_msgs::FaultInjectionSensorSrv&) { return value(); }
};


// service_traits::MD5Sum< ::morai_msgs::FaultInjectionSensorSrvRequest> should match
// service_traits::MD5Sum< ::morai_msgs::FaultInjectionSensorSrv >
template<>
struct MD5Sum< ::morai_msgs::FaultInjectionSensorSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::morai_msgs::FaultInjectionSensorSrv >::value();
  }
  static const char* value(const ::morai_msgs::FaultInjectionSensorSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::morai_msgs::FaultInjectionSensorSrvRequest> should match
// service_traits::DataType< ::morai_msgs::FaultInjectionSensorSrv >
template<>
struct DataType< ::morai_msgs::FaultInjectionSensorSrvRequest>
{
  static const char* value()
  {
    return DataType< ::morai_msgs::FaultInjectionSensorSrv >::value();
  }
  static const char* value(const ::morai_msgs::FaultInjectionSensorSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::morai_msgs::FaultInjectionSensorSrvResponse> should match
// service_traits::MD5Sum< ::morai_msgs::FaultInjectionSensorSrv >
template<>
struct MD5Sum< ::morai_msgs::FaultInjectionSensorSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::morai_msgs::FaultInjectionSensorSrv >::value();
  }
  static const char* value(const ::morai_msgs::FaultInjectionSensorSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::morai_msgs::FaultInjectionSensorSrvResponse> should match
// service_traits::DataType< ::morai_msgs::FaultInjectionSensorSrv >
template<>
struct DataType< ::morai_msgs::FaultInjectionSensorSrvResponse>
{
  static const char* value()
  {
    return DataType< ::morai_msgs::FaultInjectionSensorSrv >::value();
  }
  static const char* value(const ::morai_msgs::FaultInjectionSensorSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_FAULTINJECTIONSENSORSRV_H
