// Generated by gencpp from file morai_msgs/FaultInjectionCtrlSrv.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_FAULTINJECTIONCTRLSRV_H
#define MORAI_MSGS_MESSAGE_FAULTINJECTIONCTRLSRV_H

#include <ros/service_traits.h>


#include <morai_msgs/FaultInjectionCtrlSrvRequest.h>
#include <morai_msgs/FaultInjectionCtrlSrvResponse.h>


namespace morai_msgs
{

struct FaultInjectionCtrlSrv
{

typedef FaultInjectionCtrlSrvRequest Request;
typedef FaultInjectionCtrlSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FaultInjectionCtrlSrv
} // namespace morai_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::morai_msgs::FaultInjectionCtrlSrv > {
  static const char* value()
  {
    return "903881dc09163ac5bf8f905e4d1ee274";
  }

  static const char* value(const ::morai_msgs::FaultInjectionCtrlSrv&) { return value(); }
};

template<>
struct DataType< ::morai_msgs::FaultInjectionCtrlSrv > {
  static const char* value()
  {
    return "morai_msgs/FaultInjectionCtrlSrv";
  }

  static const char* value(const ::morai_msgs::FaultInjectionCtrlSrv&) { return value(); }
};


// service_traits::MD5Sum< ::morai_msgs::FaultInjectionCtrlSrvRequest> should match
// service_traits::MD5Sum< ::morai_msgs::FaultInjectionCtrlSrv >
template<>
struct MD5Sum< ::morai_msgs::FaultInjectionCtrlSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::morai_msgs::FaultInjectionCtrlSrv >::value();
  }
  static const char* value(const ::morai_msgs::FaultInjectionCtrlSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::morai_msgs::FaultInjectionCtrlSrvRequest> should match
// service_traits::DataType< ::morai_msgs::FaultInjectionCtrlSrv >
template<>
struct DataType< ::morai_msgs::FaultInjectionCtrlSrvRequest>
{
  static const char* value()
  {
    return DataType< ::morai_msgs::FaultInjectionCtrlSrv >::value();
  }
  static const char* value(const ::morai_msgs::FaultInjectionCtrlSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::morai_msgs::FaultInjectionCtrlSrvResponse> should match
// service_traits::MD5Sum< ::morai_msgs::FaultInjectionCtrlSrv >
template<>
struct MD5Sum< ::morai_msgs::FaultInjectionCtrlSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::morai_msgs::FaultInjectionCtrlSrv >::value();
  }
  static const char* value(const ::morai_msgs::FaultInjectionCtrlSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::morai_msgs::FaultInjectionCtrlSrvResponse> should match
// service_traits::DataType< ::morai_msgs::FaultInjectionCtrlSrv >
template<>
struct DataType< ::morai_msgs::FaultInjectionCtrlSrvResponse>
{
  static const char* value()
  {
    return DataType< ::morai_msgs::FaultInjectionCtrlSrv >::value();
  }
  static const char* value(const ::morai_msgs::FaultInjectionCtrlSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_FAULTINJECTIONCTRLSRV_H
