// Generated by gencpp from file morai_msgs/MultiPlayEventSrv.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_MULTIPLAYEVENTSRV_H
#define MORAI_MSGS_MESSAGE_MULTIPLAYEVENTSRV_H

#include <ros/service_traits.h>


#include <morai_msgs/MultiPlayEventSrvRequest.h>
#include <morai_msgs/MultiPlayEventSrvResponse.h>


namespace morai_msgs
{

struct MultiPlayEventSrv
{

typedef MultiPlayEventSrvRequest Request;
typedef MultiPlayEventSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MultiPlayEventSrv
} // namespace morai_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::morai_msgs::MultiPlayEventSrv > {
  static const char* value()
  {
    return "5ff2047bbd823c7a4e40fc93cb1bb42d";
  }

  static const char* value(const ::morai_msgs::MultiPlayEventSrv&) { return value(); }
};

template<>
struct DataType< ::morai_msgs::MultiPlayEventSrv > {
  static const char* value()
  {
    return "morai_msgs/MultiPlayEventSrv";
  }

  static const char* value(const ::morai_msgs::MultiPlayEventSrv&) { return value(); }
};


// service_traits::MD5Sum< ::morai_msgs::MultiPlayEventSrvRequest> should match
// service_traits::MD5Sum< ::morai_msgs::MultiPlayEventSrv >
template<>
struct MD5Sum< ::morai_msgs::MultiPlayEventSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::morai_msgs::MultiPlayEventSrv >::value();
  }
  static const char* value(const ::morai_msgs::MultiPlayEventSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::morai_msgs::MultiPlayEventSrvRequest> should match
// service_traits::DataType< ::morai_msgs::MultiPlayEventSrv >
template<>
struct DataType< ::morai_msgs::MultiPlayEventSrvRequest>
{
  static const char* value()
  {
    return DataType< ::morai_msgs::MultiPlayEventSrv >::value();
  }
  static const char* value(const ::morai_msgs::MultiPlayEventSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::morai_msgs::MultiPlayEventSrvResponse> should match
// service_traits::MD5Sum< ::morai_msgs::MultiPlayEventSrv >
template<>
struct MD5Sum< ::morai_msgs::MultiPlayEventSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::morai_msgs::MultiPlayEventSrv >::value();
  }
  static const char* value(const ::morai_msgs::MultiPlayEventSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::morai_msgs::MultiPlayEventSrvResponse> should match
// service_traits::DataType< ::morai_msgs::MultiPlayEventSrv >
template<>
struct DataType< ::morai_msgs::MultiPlayEventSrvResponse>
{
  static const char* value()
  {
    return DataType< ::morai_msgs::MultiPlayEventSrv >::value();
  }
  static const char* value(const ::morai_msgs::MultiPlayEventSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_MULTIPLAYEVENTSRV_H
