// Generated by gencpp from file morai_msgs/SVADC.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_SVADC_H
#define MORAI_MSGS_MESSAGE_SVADC_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace morai_msgs
{
template <class ContainerAllocator>
struct SVADC_
{
  typedef SVADC_<ContainerAllocator> Type;

  SVADC_()
    : header()
    , collisionCount(0)
    , signalViolationCount(0)
    , speedLimitCount(0)  {
    }
  SVADC_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , collisionCount(0)
    , signalViolationCount(0)
    , speedLimitCount(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _collisionCount_type;
  _collisionCount_type collisionCount;

   typedef int32_t _signalViolationCount_type;
  _signalViolationCount_type signalViolationCount;

   typedef int32_t _speedLimitCount_type;
  _speedLimitCount_type speedLimitCount;





  typedef boost::shared_ptr< ::morai_msgs::SVADC_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::SVADC_<ContainerAllocator> const> ConstPtr;

}; // struct SVADC_

typedef ::morai_msgs::SVADC_<std::allocator<void> > SVADC;

typedef boost::shared_ptr< ::morai_msgs::SVADC > SVADCPtr;
typedef boost::shared_ptr< ::morai_msgs::SVADC const> SVADCConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::SVADC_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::SVADC_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::SVADC_<ContainerAllocator1> & lhs, const ::morai_msgs::SVADC_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.collisionCount == rhs.collisionCount &&
    lhs.signalViolationCount == rhs.signalViolationCount &&
    lhs.speedLimitCount == rhs.speedLimitCount;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::SVADC_<ContainerAllocator1> & lhs, const ::morai_msgs::SVADC_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::SVADC_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::SVADC_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::SVADC_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::SVADC_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::SVADC_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::SVADC_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::SVADC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c180496093e554e39b1b25419d7fdd6e";
  }

  static const char* value(const ::morai_msgs::SVADC_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc180496093e554e3ULL;
  static const uint64_t static_value2 = 0x9b1b25419d7fdd6eULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::SVADC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/SVADC";
  }

  static const char* value(const ::morai_msgs::SVADC_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::SVADC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 collisionCount\n"
"int32 signalViolationCount\n"
"int32 speedLimitCount\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::morai_msgs::SVADC_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::SVADC_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.collisionCount);
      stream.next(m.signalViolationCount);
      stream.next(m.speedLimitCount);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SVADC_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::SVADC_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::SVADC_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "collisionCount: ";
    Printer<int32_t>::stream(s, indent + "  ", v.collisionCount);
    s << indent << "signalViolationCount: ";
    Printer<int32_t>::stream(s, indent + "  ", v.signalViolationCount);
    s << indent << "speedLimitCount: ";
    Printer<int32_t>::stream(s, indent + "  ", v.speedLimitCount);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_SVADC_H
