// Generated by gencpp from file morai_msgs/WoowaDillyStatus.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_WOOWADILLYSTATUS_H
#define MORAI_MSGS_MESSAGE_WOOWADILLYSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace morai_msgs
{
template <class ContainerAllocator>
struct WoowaDillyStatus_
{
  typedef WoowaDillyStatus_<ContainerAllocator> Type;

  WoowaDillyStatus_()
    : header()
    , deliveryItem()  {
    }
  WoowaDillyStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , deliveryItem(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _deliveryItem_type;
  _deliveryItem_type deliveryItem;





  typedef boost::shared_ptr< ::morai_msgs::WoowaDillyStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::WoowaDillyStatus_<ContainerAllocator> const> ConstPtr;

}; // struct WoowaDillyStatus_

typedef ::morai_msgs::WoowaDillyStatus_<std::allocator<void> > WoowaDillyStatus;

typedef boost::shared_ptr< ::morai_msgs::WoowaDillyStatus > WoowaDillyStatusPtr;
typedef boost::shared_ptr< ::morai_msgs::WoowaDillyStatus const> WoowaDillyStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::WoowaDillyStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::WoowaDillyStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::WoowaDillyStatus_<ContainerAllocator1> & lhs, const ::morai_msgs::WoowaDillyStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.deliveryItem == rhs.deliveryItem;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::WoowaDillyStatus_<ContainerAllocator1> & lhs, const ::morai_msgs::WoowaDillyStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::WoowaDillyStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::WoowaDillyStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::WoowaDillyStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::WoowaDillyStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::WoowaDillyStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::WoowaDillyStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::WoowaDillyStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "336610afe157caca7c85fe22948c1ded";
  }

  static const char* value(const ::morai_msgs::WoowaDillyStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x336610afe157cacaULL;
  static const uint64_t static_value2 = 0x7c85fe22948c1dedULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::WoowaDillyStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/WoowaDillyStatus";
  }

  static const char* value(const ::morai_msgs::WoowaDillyStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::WoowaDillyStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32[] deliveryItem\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::morai_msgs::WoowaDillyStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::WoowaDillyStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.deliveryItem);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WoowaDillyStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::WoowaDillyStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::WoowaDillyStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "deliveryItem[]" << std::endl;
    for (size_t i = 0; i < v.deliveryItem.size(); ++i)
    {
      s << indent << "  deliveryItem[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.deliveryItem[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_WOOWADILLYSTATUS_H
