# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from morai_msgs/FaultInjectionTireSrvRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import morai_msgs.msg

class FaultInjectionTireSrvRequest(genpy.Message):
  _md5sum = "a7e45a698065b4e4cdd3e6ff1dc6b614"
  _type = "morai_msgs/FaultInjectionTireSrvRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """FaultInjection_Tire request

================================================================================
MSG: morai_msgs/FaultInjection_Tire
int32 unique_id
int32 tire_index

int32 fault_class
int32 fault_subclass
"""
  __slots__ = ['request']
  _slot_types = ['morai_msgs/FaultInjection_Tire']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       request

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FaultInjectionTireSrvRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.request is None:
        self.request = morai_msgs.msg.FaultInjection_Tire()
    else:
      self.request = morai_msgs.msg.FaultInjection_Tire()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4i().pack(_x.request.unique_id, _x.request.tire_index, _x.request.fault_class, _x.request.fault_subclass))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.request is None:
        self.request = morai_msgs.msg.FaultInjection_Tire()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.request.unique_id, _x.request.tire_index, _x.request.fault_class, _x.request.fault_subclass,) = _get_struct_4i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4i().pack(_x.request.unique_id, _x.request.tire_index, _x.request.fault_class, _x.request.fault_subclass))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.request is None:
        self.request = morai_msgs.msg.FaultInjection_Tire()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.request.unique_id, _x.request.tire_index, _x.request.fault_class, _x.request.fault_subclass,) = _get_struct_4i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4i = None
def _get_struct_4i():
    global _struct_4i
    if _struct_4i is None:
        _struct_4i = struct.Struct("<4i")
    return _struct_4i
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from morai_msgs/FaultInjectionTireSrvResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import morai_msgs.msg

class FaultInjectionTireSrvResponse(genpy.Message):
  _md5sum = "b095c5b66e667567179177eaff1ea884"
  _type = "morai_msgs/FaultInjectionTireSrvResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """FaultInjection_Response response


================================================================================
MSG: morai_msgs/FaultInjection_Response
bool result

int32 unique_id
FaultStatusInfo_Vehicle vehicle
FaultStatusInfo_Sensor[] sensors

================================================================================
MSG: morai_msgs/FaultStatusInfo_Vehicle
FaultStatusInfo_Overall accel
FaultStatusInfo_Overall brake
FaultStatusInfo_Overall steer
FaultStatusInfo_Overall[] tires


================================================================================
MSG: morai_msgs/FaultStatusInfo_Overall
bool status
int32[] fault_subclass

================================================================================
MSG: morai_msgs/FaultStatusInfo_Sensor
int32 sensor_id
FaultStatusInfo_Overall sensor

"""
  __slots__ = ['response']
  _slot_types = ['morai_msgs/FaultInjection_Response']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       response

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FaultInjectionTireSrvResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.response is None:
        self.response = morai_msgs.msg.FaultInjection_Response()
    else:
      self.response = morai_msgs.msg.FaultInjection_Response()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_BiB().pack(_x.response.result, _x.response.unique_id, _x.response.vehicle.accel.status))
      length = len(self.response.vehicle.accel.fault_subclass)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.response.vehicle.accel.fault_subclass))
      _x = self.response.vehicle.brake.status
      buff.write(_get_struct_B().pack(_x))
      length = len(self.response.vehicle.brake.fault_subclass)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.response.vehicle.brake.fault_subclass))
      _x = self.response.vehicle.steer.status
      buff.write(_get_struct_B().pack(_x))
      length = len(self.response.vehicle.steer.fault_subclass)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.response.vehicle.steer.fault_subclass))
      length = len(self.response.vehicle.tires)
      buff.write(_struct_I.pack(length))
      for val1 in self.response.vehicle.tires:
        _x = val1.status
        buff.write(_get_struct_B().pack(_x))
        length = len(val1.fault_subclass)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(struct.Struct(pattern).pack(*val1.fault_subclass))
      length = len(self.response.sensors)
      buff.write(_struct_I.pack(length))
      for val1 in self.response.sensors:
        _x = val1.sensor_id
        buff.write(_get_struct_i().pack(_x))
        _v1 = val1.sensor
        _x = _v1.status
        buff.write(_get_struct_B().pack(_x))
        length = len(_v1.fault_subclass)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(struct.Struct(pattern).pack(*_v1.fault_subclass))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.response is None:
        self.response = morai_msgs.msg.FaultInjection_Response()
      end = 0
      _x = self
      start = end
      end += 6
      (_x.response.result, _x.response.unique_id, _x.response.vehicle.accel.status,) = _get_struct_BiB().unpack(str[start:end])
      self.response.result = bool(self.response.result)
      self.response.vehicle.accel.status = bool(self.response.vehicle.accel.status)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.response.vehicle.accel.fault_subclass = s.unpack(str[start:end])
      start = end
      end += 1
      (self.response.vehicle.brake.status,) = _get_struct_B().unpack(str[start:end])
      self.response.vehicle.brake.status = bool(self.response.vehicle.brake.status)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.response.vehicle.brake.fault_subclass = s.unpack(str[start:end])
      start = end
      end += 1
      (self.response.vehicle.steer.status,) = _get_struct_B().unpack(str[start:end])
      self.response.vehicle.steer.status = bool(self.response.vehicle.steer.status)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.response.vehicle.steer.fault_subclass = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.response.vehicle.tires = []
      for i in range(0, length):
        val1 = morai_msgs.msg.FaultStatusInfo_Overall()
        start = end
        end += 1
        (val1.status,) = _get_struct_B().unpack(str[start:end])
        val1.status = bool(val1.status)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.fault_subclass = s.unpack(str[start:end])
        self.response.vehicle.tires.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.response.sensors = []
      for i in range(0, length):
        val1 = morai_msgs.msg.FaultStatusInfo_Sensor()
        start = end
        end += 4
        (val1.sensor_id,) = _get_struct_i().unpack(str[start:end])
        _v2 = val1.sensor
        start = end
        end += 1
        (_v2.status,) = _get_struct_B().unpack(str[start:end])
        _v2.status = bool(_v2.status)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        _v2.fault_subclass = s.unpack(str[start:end])
        self.response.sensors.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_BiB().pack(_x.response.result, _x.response.unique_id, _x.response.vehicle.accel.status))
      length = len(self.response.vehicle.accel.fault_subclass)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.response.vehicle.accel.fault_subclass.tostring())
      _x = self.response.vehicle.brake.status
      buff.write(_get_struct_B().pack(_x))
      length = len(self.response.vehicle.brake.fault_subclass)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.response.vehicle.brake.fault_subclass.tostring())
      _x = self.response.vehicle.steer.status
      buff.write(_get_struct_B().pack(_x))
      length = len(self.response.vehicle.steer.fault_subclass)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.response.vehicle.steer.fault_subclass.tostring())
      length = len(self.response.vehicle.tires)
      buff.write(_struct_I.pack(length))
      for val1 in self.response.vehicle.tires:
        _x = val1.status
        buff.write(_get_struct_B().pack(_x))
        length = len(val1.fault_subclass)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(val1.fault_subclass.tostring())
      length = len(self.response.sensors)
      buff.write(_struct_I.pack(length))
      for val1 in self.response.sensors:
        _x = val1.sensor_id
        buff.write(_get_struct_i().pack(_x))
        _v3 = val1.sensor
        _x = _v3.status
        buff.write(_get_struct_B().pack(_x))
        length = len(_v3.fault_subclass)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(_v3.fault_subclass.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.response is None:
        self.response = morai_msgs.msg.FaultInjection_Response()
      end = 0
      _x = self
      start = end
      end += 6
      (_x.response.result, _x.response.unique_id, _x.response.vehicle.accel.status,) = _get_struct_BiB().unpack(str[start:end])
      self.response.result = bool(self.response.result)
      self.response.vehicle.accel.status = bool(self.response.vehicle.accel.status)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.response.vehicle.accel.fault_subclass = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 1
      (self.response.vehicle.brake.status,) = _get_struct_B().unpack(str[start:end])
      self.response.vehicle.brake.status = bool(self.response.vehicle.brake.status)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.response.vehicle.brake.fault_subclass = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 1
      (self.response.vehicle.steer.status,) = _get_struct_B().unpack(str[start:end])
      self.response.vehicle.steer.status = bool(self.response.vehicle.steer.status)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.response.vehicle.steer.fault_subclass = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.response.vehicle.tires = []
      for i in range(0, length):
        val1 = morai_msgs.msg.FaultStatusInfo_Overall()
        start = end
        end += 1
        (val1.status,) = _get_struct_B().unpack(str[start:end])
        val1.status = bool(val1.status)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.fault_subclass = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
        self.response.vehicle.tires.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.response.sensors = []
      for i in range(0, length):
        val1 = morai_msgs.msg.FaultStatusInfo_Sensor()
        start = end
        end += 4
        (val1.sensor_id,) = _get_struct_i().unpack(str[start:end])
        _v4 = val1.sensor
        start = end
        end += 1
        (_v4.status,) = _get_struct_B().unpack(str[start:end])
        _v4.status = bool(_v4.status)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        _v4.fault_subclass = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
        self.response.sensors.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_BiB = None
def _get_struct_BiB():
    global _struct_BiB
    if _struct_BiB is None:
        _struct_BiB = struct.Struct("<BiB")
    return _struct_BiB
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
class FaultInjectionTireSrv(object):
  _type          = 'morai_msgs/FaultInjectionTireSrv'
  _md5sum = '4c1cd51f8732dd56891a353f6f931b8a'
  _request_class  = FaultInjectionTireSrvRequest
  _response_class = FaultInjectionTireSrvResponse
