# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from morai_msgs/FaultStatusInfo_Sensor.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import morai_msgs.msg

class FaultStatusInfo_Sensor(genpy.Message):
  _md5sum = "9ffcbdb400d2f73cb504fbb8f540f234"
  _type = "morai_msgs/FaultStatusInfo_Sensor"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 sensor_id
FaultStatusInfo_Overall sensor


================================================================================
MSG: morai_msgs/FaultStatusInfo_Overall
bool status
int32[] fault_subclass
"""
  __slots__ = ['sensor_id','sensor']
  _slot_types = ['int32','morai_msgs/FaultStatusInfo_Overall']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sensor_id,sensor

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FaultStatusInfo_Sensor, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.sensor_id is None:
        self.sensor_id = 0
      if self.sensor is None:
        self.sensor = morai_msgs.msg.FaultStatusInfo_Overall()
    else:
      self.sensor_id = 0
      self.sensor = morai_msgs.msg.FaultStatusInfo_Overall()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_iB().pack(_x.sensor_id, _x.sensor.status))
      length = len(self.sensor.fault_subclass)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.sensor.fault_subclass))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.sensor is None:
        self.sensor = morai_msgs.msg.FaultStatusInfo_Overall()
      end = 0
      _x = self
      start = end
      end += 5
      (_x.sensor_id, _x.sensor.status,) = _get_struct_iB().unpack(str[start:end])
      self.sensor.status = bool(self.sensor.status)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.sensor.fault_subclass = s.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_iB().pack(_x.sensor_id, _x.sensor.status))
      length = len(self.sensor.fault_subclass)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.sensor.fault_subclass.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.sensor is None:
        self.sensor = morai_msgs.msg.FaultStatusInfo_Overall()
      end = 0
      _x = self
      start = end
      end += 5
      (_x.sensor_id, _x.sensor.status,) = _get_struct_iB().unpack(str[start:end])
      self.sensor.status = bool(self.sensor.status)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.sensor.fault_subclass = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_iB = None
def _get_struct_iB():
    global _struct_iB
    if _struct_iB is None:
        _struct_iB = struct.Struct("<iB")
    return _struct_iB
