# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from morai_msgs/FaultInjection_Sensor.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class FaultInjection_Sensor(genpy.Message):
  _md5sum = "1d09067e718a7214f8177394317316b2"
  _type = "morai_msgs/FaultInjection_Sensor"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 unique_id
int32 sensor_id

int32 fault_class
int32 fault_subclass

geometry_msgs/Vector3 local_position_offset
geometry_msgs/Vector3 local_rotation_offset

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['unique_id','sensor_id','fault_class','fault_subclass','local_position_offset','local_rotation_offset']
  _slot_types = ['int32','int32','int32','int32','geometry_msgs/Vector3','geometry_msgs/Vector3']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       unique_id,sensor_id,fault_class,fault_subclass,local_position_offset,local_rotation_offset

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FaultInjection_Sensor, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.unique_id is None:
        self.unique_id = 0
      if self.sensor_id is None:
        self.sensor_id = 0
      if self.fault_class is None:
        self.fault_class = 0
      if self.fault_subclass is None:
        self.fault_subclass = 0
      if self.local_position_offset is None:
        self.local_position_offset = geometry_msgs.msg.Vector3()
      if self.local_rotation_offset is None:
        self.local_rotation_offset = geometry_msgs.msg.Vector3()
    else:
      self.unique_id = 0
      self.sensor_id = 0
      self.fault_class = 0
      self.fault_subclass = 0
      self.local_position_offset = geometry_msgs.msg.Vector3()
      self.local_rotation_offset = geometry_msgs.msg.Vector3()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4i6d().pack(_x.unique_id, _x.sensor_id, _x.fault_class, _x.fault_subclass, _x.local_position_offset.x, _x.local_position_offset.y, _x.local_position_offset.z, _x.local_rotation_offset.x, _x.local_rotation_offset.y, _x.local_rotation_offset.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.local_position_offset is None:
        self.local_position_offset = geometry_msgs.msg.Vector3()
      if self.local_rotation_offset is None:
        self.local_rotation_offset = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 64
      (_x.unique_id, _x.sensor_id, _x.fault_class, _x.fault_subclass, _x.local_position_offset.x, _x.local_position_offset.y, _x.local_position_offset.z, _x.local_rotation_offset.x, _x.local_rotation_offset.y, _x.local_rotation_offset.z,) = _get_struct_4i6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4i6d().pack(_x.unique_id, _x.sensor_id, _x.fault_class, _x.fault_subclass, _x.local_position_offset.x, _x.local_position_offset.y, _x.local_position_offset.z, _x.local_rotation_offset.x, _x.local_rotation_offset.y, _x.local_rotation_offset.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.local_position_offset is None:
        self.local_position_offset = geometry_msgs.msg.Vector3()
      if self.local_rotation_offset is None:
        self.local_rotation_offset = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 64
      (_x.unique_id, _x.sensor_id, _x.fault_class, _x.fault_subclass, _x.local_position_offset.x, _x.local_position_offset.y, _x.local_position_offset.z, _x.local_rotation_offset.x, _x.local_rotation_offset.y, _x.local_rotation_offset.z,) = _get_struct_4i6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4i6d = None
def _get_struct_4i6d():
    global _struct_4i6d
    if _struct_4i6d is None:
        _struct_4i6d = struct.Struct("<4i6d")
    return _struct_4i6d
