# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from morai_msgs/SkidSteer6wUGVStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class SkidSteer6wUGVStatus(genpy.Message):
  _md5sum = "d741d34a68b143895b122f334a1afe31"
  _type = "morai_msgs/SkidSteer6wUGVStatus"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

int32 unique_id
int32 ctrl_mode

geometry_msgs/Vector3 acceleration
geometry_msgs/Vector3 position
geometry_msgs/Vector3 linear_velocity
geometry_msgs/Vector3 angular_velocity

float64 heading
int32 cmd_type

float64 left_front_wheel_rpm
float64 left_middle_wheel_rpm
float64 left_rear_wheel_rpm
float64 right_front_wheel_rpm
float64 right_middle_wheel_rpm
float64 right_rear_wheel_rpm

float64 lateral_offset

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['header','unique_id','ctrl_mode','acceleration','position','linear_velocity','angular_velocity','heading','cmd_type','left_front_wheel_rpm','left_middle_wheel_rpm','left_rear_wheel_rpm','right_front_wheel_rpm','right_middle_wheel_rpm','right_rear_wheel_rpm','lateral_offset']
  _slot_types = ['std_msgs/Header','int32','int32','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','float64','int32','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,unique_id,ctrl_mode,acceleration,position,linear_velocity,angular_velocity,heading,cmd_type,left_front_wheel_rpm,left_middle_wheel_rpm,left_rear_wheel_rpm,right_front_wheel_rpm,right_middle_wheel_rpm,right_rear_wheel_rpm,lateral_offset

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SkidSteer6wUGVStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.unique_id is None:
        self.unique_id = 0
      if self.ctrl_mode is None:
        self.ctrl_mode = 0
      if self.acceleration is None:
        self.acceleration = geometry_msgs.msg.Vector3()
      if self.position is None:
        self.position = geometry_msgs.msg.Vector3()
      if self.linear_velocity is None:
        self.linear_velocity = geometry_msgs.msg.Vector3()
      if self.angular_velocity is None:
        self.angular_velocity = geometry_msgs.msg.Vector3()
      if self.heading is None:
        self.heading = 0.
      if self.cmd_type is None:
        self.cmd_type = 0
      if self.left_front_wheel_rpm is None:
        self.left_front_wheel_rpm = 0.
      if self.left_middle_wheel_rpm is None:
        self.left_middle_wheel_rpm = 0.
      if self.left_rear_wheel_rpm is None:
        self.left_rear_wheel_rpm = 0.
      if self.right_front_wheel_rpm is None:
        self.right_front_wheel_rpm = 0.
      if self.right_middle_wheel_rpm is None:
        self.right_middle_wheel_rpm = 0.
      if self.right_rear_wheel_rpm is None:
        self.right_rear_wheel_rpm = 0.
      if self.lateral_offset is None:
        self.lateral_offset = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.unique_id = 0
      self.ctrl_mode = 0
      self.acceleration = geometry_msgs.msg.Vector3()
      self.position = geometry_msgs.msg.Vector3()
      self.linear_velocity = geometry_msgs.msg.Vector3()
      self.angular_velocity = geometry_msgs.msg.Vector3()
      self.heading = 0.
      self.cmd_type = 0
      self.left_front_wheel_rpm = 0.
      self.left_middle_wheel_rpm = 0.
      self.left_rear_wheel_rpm = 0.
      self.right_front_wheel_rpm = 0.
      self.right_middle_wheel_rpm = 0.
      self.right_rear_wheel_rpm = 0.
      self.lateral_offset = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2i13di7d().pack(_x.unique_id, _x.ctrl_mode, _x.acceleration.x, _x.acceleration.y, _x.acceleration.z, _x.position.x, _x.position.y, _x.position.z, _x.linear_velocity.x, _x.linear_velocity.y, _x.linear_velocity.z, _x.angular_velocity.x, _x.angular_velocity.y, _x.angular_velocity.z, _x.heading, _x.cmd_type, _x.left_front_wheel_rpm, _x.left_middle_wheel_rpm, _x.left_rear_wheel_rpm, _x.right_front_wheel_rpm, _x.right_middle_wheel_rpm, _x.right_rear_wheel_rpm, _x.lateral_offset))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.acceleration is None:
        self.acceleration = geometry_msgs.msg.Vector3()
      if self.position is None:
        self.position = geometry_msgs.msg.Vector3()
      if self.linear_velocity is None:
        self.linear_velocity = geometry_msgs.msg.Vector3()
      if self.angular_velocity is None:
        self.angular_velocity = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 172
      (_x.unique_id, _x.ctrl_mode, _x.acceleration.x, _x.acceleration.y, _x.acceleration.z, _x.position.x, _x.position.y, _x.position.z, _x.linear_velocity.x, _x.linear_velocity.y, _x.linear_velocity.z, _x.angular_velocity.x, _x.angular_velocity.y, _x.angular_velocity.z, _x.heading, _x.cmd_type, _x.left_front_wheel_rpm, _x.left_middle_wheel_rpm, _x.left_rear_wheel_rpm, _x.right_front_wheel_rpm, _x.right_middle_wheel_rpm, _x.right_rear_wheel_rpm, _x.lateral_offset,) = _get_struct_2i13di7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2i13di7d().pack(_x.unique_id, _x.ctrl_mode, _x.acceleration.x, _x.acceleration.y, _x.acceleration.z, _x.position.x, _x.position.y, _x.position.z, _x.linear_velocity.x, _x.linear_velocity.y, _x.linear_velocity.z, _x.angular_velocity.x, _x.angular_velocity.y, _x.angular_velocity.z, _x.heading, _x.cmd_type, _x.left_front_wheel_rpm, _x.left_middle_wheel_rpm, _x.left_rear_wheel_rpm, _x.right_front_wheel_rpm, _x.right_middle_wheel_rpm, _x.right_rear_wheel_rpm, _x.lateral_offset))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.acceleration is None:
        self.acceleration = geometry_msgs.msg.Vector3()
      if self.position is None:
        self.position = geometry_msgs.msg.Vector3()
      if self.linear_velocity is None:
        self.linear_velocity = geometry_msgs.msg.Vector3()
      if self.angular_velocity is None:
        self.angular_velocity = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 172
      (_x.unique_id, _x.ctrl_mode, _x.acceleration.x, _x.acceleration.y, _x.acceleration.z, _x.position.x, _x.position.y, _x.position.z, _x.linear_velocity.x, _x.linear_velocity.y, _x.linear_velocity.z, _x.angular_velocity.x, _x.angular_velocity.y, _x.angular_velocity.z, _x.heading, _x.cmd_type, _x.left_front_wheel_rpm, _x.left_middle_wheel_rpm, _x.left_rear_wheel_rpm, _x.right_front_wheel_rpm, _x.right_middle_wheel_rpm, _x.right_rear_wheel_rpm, _x.lateral_offset,) = _get_struct_2i13di7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i13di7d = None
def _get_struct_2i13di7d():
    global _struct_2i13di7d
    if _struct_2i13di7d is None:
        _struct_2i13di7d = struct.Struct("<2i13di7d")
    return _struct_2i13di7d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
