# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from morai_msgs/FaultStatusInfo_Vehicle.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import morai_msgs.msg

class FaultStatusInfo_Vehicle(genpy.Message):
  _md5sum = "dcd69cdf7980329f2014366617eda419"
  _type = "morai_msgs/FaultStatusInfo_Vehicle"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """FaultStatusInfo_Overall accel
FaultStatusInfo_Overall brake
FaultStatusInfo_Overall steer
FaultStatusInfo_Overall[] tires


================================================================================
MSG: morai_msgs/FaultStatusInfo_Overall
bool status
int32[] fault_subclass
"""
  __slots__ = ['accel','brake','steer','tires']
  _slot_types = ['morai_msgs/FaultStatusInfo_Overall','morai_msgs/FaultStatusInfo_Overall','morai_msgs/FaultStatusInfo_Overall','morai_msgs/FaultStatusInfo_Overall[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       accel,brake,steer,tires

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FaultStatusInfo_Vehicle, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.accel is None:
        self.accel = morai_msgs.msg.FaultStatusInfo_Overall()
      if self.brake is None:
        self.brake = morai_msgs.msg.FaultStatusInfo_Overall()
      if self.steer is None:
        self.steer = morai_msgs.msg.FaultStatusInfo_Overall()
      if self.tires is None:
        self.tires = []
    else:
      self.accel = morai_msgs.msg.FaultStatusInfo_Overall()
      self.brake = morai_msgs.msg.FaultStatusInfo_Overall()
      self.steer = morai_msgs.msg.FaultStatusInfo_Overall()
      self.tires = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.accel.status
      buff.write(_get_struct_B().pack(_x))
      length = len(self.accel.fault_subclass)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.accel.fault_subclass))
      _x = self.brake.status
      buff.write(_get_struct_B().pack(_x))
      length = len(self.brake.fault_subclass)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.brake.fault_subclass))
      _x = self.steer.status
      buff.write(_get_struct_B().pack(_x))
      length = len(self.steer.fault_subclass)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.steer.fault_subclass))
      length = len(self.tires)
      buff.write(_struct_I.pack(length))
      for val1 in self.tires:
        _x = val1.status
        buff.write(_get_struct_B().pack(_x))
        length = len(val1.fault_subclass)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(struct.Struct(pattern).pack(*val1.fault_subclass))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.accel is None:
        self.accel = morai_msgs.msg.FaultStatusInfo_Overall()
      if self.brake is None:
        self.brake = morai_msgs.msg.FaultStatusInfo_Overall()
      if self.steer is None:
        self.steer = morai_msgs.msg.FaultStatusInfo_Overall()
      if self.tires is None:
        self.tires = None
      end = 0
      start = end
      end += 1
      (self.accel.status,) = _get_struct_B().unpack(str[start:end])
      self.accel.status = bool(self.accel.status)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.accel.fault_subclass = s.unpack(str[start:end])
      start = end
      end += 1
      (self.brake.status,) = _get_struct_B().unpack(str[start:end])
      self.brake.status = bool(self.brake.status)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.brake.fault_subclass = s.unpack(str[start:end])
      start = end
      end += 1
      (self.steer.status,) = _get_struct_B().unpack(str[start:end])
      self.steer.status = bool(self.steer.status)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.steer.fault_subclass = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.tires = []
      for i in range(0, length):
        val1 = morai_msgs.msg.FaultStatusInfo_Overall()
        start = end
        end += 1
        (val1.status,) = _get_struct_B().unpack(str[start:end])
        val1.status = bool(val1.status)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.fault_subclass = s.unpack(str[start:end])
        self.tires.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.accel.status
      buff.write(_get_struct_B().pack(_x))
      length = len(self.accel.fault_subclass)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.accel.fault_subclass.tostring())
      _x = self.brake.status
      buff.write(_get_struct_B().pack(_x))
      length = len(self.brake.fault_subclass)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.brake.fault_subclass.tostring())
      _x = self.steer.status
      buff.write(_get_struct_B().pack(_x))
      length = len(self.steer.fault_subclass)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.steer.fault_subclass.tostring())
      length = len(self.tires)
      buff.write(_struct_I.pack(length))
      for val1 in self.tires:
        _x = val1.status
        buff.write(_get_struct_B().pack(_x))
        length = len(val1.fault_subclass)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(val1.fault_subclass.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.accel is None:
        self.accel = morai_msgs.msg.FaultStatusInfo_Overall()
      if self.brake is None:
        self.brake = morai_msgs.msg.FaultStatusInfo_Overall()
      if self.steer is None:
        self.steer = morai_msgs.msg.FaultStatusInfo_Overall()
      if self.tires is None:
        self.tires = None
      end = 0
      start = end
      end += 1
      (self.accel.status,) = _get_struct_B().unpack(str[start:end])
      self.accel.status = bool(self.accel.status)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.accel.fault_subclass = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 1
      (self.brake.status,) = _get_struct_B().unpack(str[start:end])
      self.brake.status = bool(self.brake.status)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.brake.fault_subclass = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 1
      (self.steer.status,) = _get_struct_B().unpack(str[start:end])
      self.steer.status = bool(self.steer.status)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.steer.fault_subclass = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.tires = []
      for i in range(0, length):
        val1 = morai_msgs.msg.FaultStatusInfo_Overall()
        start = end
        end += 1
        (val1.status,) = _get_struct_B().unpack(str[start:end])
        val1.status = bool(val1.status)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.fault_subclass = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
        self.tires.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
