(cl:in-package morai_msgs-msg)
(cl:export '(CMD_TYPE-VAL
          CMD_TYPE
          FORWARD_INPUT-VAL
          FORWARD_INPUT
          BACKWARD_INPUT-VAL
          BACKWARD_INPUT
          LEFT_TURN_INPUT-VAL
          LEFT_TURN_INPUT
          RIGHT_TURN_INPUT-VAL
          RIGHT_TURN_INPUT
          LEFT_FRONT_WHEEL_RPM-VAL
          LEFT_FRONT_WHEEL_RPM
          LEFT_MIDDLE_WHEEL_RPM-VAL
          LEFT_MIDDLE_WHEEL_RPM
          LEFT_REAR_WHEEL_RPM-VAL
          LEFT_REAR_WHEEL_RPM
          RIGHT_FRONT_WHEEL_RPM-VAL
          RIGHT_FRONT_WHEEL_RPM
          RIGHT_MIDDLE_WHEEL_RPM-VAL
          RIGHT_MIDDLE_WHEEL_RPM
          RIGHT_REAR_WHEEL_RPM-VAL
          RIGHT_REAR_WHEEL_RPM
          TARGET_LINEAR_VELOCITY-VAL
          TARGET_LINEAR_VELOCITY
          TARGET_ANGULAR_VELOCITY-VAL
          TARGET_ANGULAR_VELOCITY
))